cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
https://maulanarizky-store-disini.rizkyxd.me/ip.php
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
php tes.php
cd /sdcard/p
.php
cd /sdcard/p
php index.php
cd /sdcard/d
phpnindex.php
php index.php
cd /sdcard/d
php index.php
cd /sdcard/d
php index.php
cd /sdcard/e
php index.php
cd /sdcard/e
php index.php
cd /sdcard/e
php index.php
ssh livin@20.93.7.198
ssh root@20.93.7.198
https://haduh.livinsesi.my.id/apiii.php
php index.php
ssh aryaa@4.227.159.55
ssh arya@4.227.159.55
cd /sdcard/p
php index.php
ssh root@157.230.242.27
cd /sdcard/p
php index.php
cd /sdcard/p
php index.php
cd /sdcard/p
php index.php
cd /sdcard/d
php index.php
ssh ubuhtu@146.59.86.223
ssh ubuntu@146.59.86.22
cd /sdcard/e
pho index.php
php index.php
